title: kirby.xyz
description: >
  The personal webpage of Kirby Kohlmorgen.
baseurl: ""
url: "http://kirby.xyz" # the base hostname & protocol for your site
permalink: "/:title"

markdown: kramdown
highlighter: pygments
